-- ENPEI – École Nationale Préparatoire aux Études d'Ingénieur (Rouiba)
INSERT INTO institutions (
  name, slug, category, sub_category,
  wilaya, commune, address,
  website_url, contact_email, facebook_page, instagram_username,
  bac_required, diploma_type, mesrs_recognized, intl_equivalence,
  languages, annual_cost_range, admission_type, promo_size,
  internship_provided, internship_duration,
  programmes, real_outcomes, insertion_rate, passerelles,
  corporate_partners, school_partners,
  boarding_available, transport_available, canteen_available, elearning_platform,
  data_confidence, is_active
)
VALUES (
  'ENPEI – École Nationale Préparatoire aux Études d''Ingénieur',
  'enpei-ecole-nationale-preparatoire-etudes-ingenieur-rouiba',
  'Superieur',
  'Classe préparatoire publique',
  'Alger',
  'Rouiba',
  'Rouiba, Alger (zone industrielle)',
  'https://enpei.dz',
  NULL,
  NULL,
  NULL,
  TRUE,
  'Classe préparatoire de 2 ans orientée profils industriels, pour préparer l''entrée à l''ENP, l''ENTP et l''ENST.',
  TRUE,
  'Reconnu comme voie de préparation officielle vers les grandes écoles d''ingénieurs industrielles (génie mécanique, civil, électrotechnique).',
  ARRAY['FR'],
  'Quasi-gratuit : droits 200 DA/an, bourse automatique, internat et restauration.',
  'Admission sélective : Bac Maths ou Tech-Maths avec moyenne ≥13/20.',
  '2 ans de préparation intensive avant le CNC.',
  FALSE,
  NULL,
  'Maths, physique, chimie, mécanique, bases de génie civil et électrotechnique.',
  'Débouchés conditionnés par la réussite aux concours : intégration de l''ENP, de l''ENTP et de l''ENST (profils industriels).',
  'Taux d''insertion indirect estimé élevé pour les admis dans ces écoles (fort besoin en ingénieurs industriels).',
  'Passerelles vers ENP, ENTP et ENST après réussite du CNC.',
  '["ENP","ENTP","ENST","Entreprises industrielles partenaires"]'::jsonb,
  '["Réseau national des écoles préparatoires et grandes écoles d''ingénieurs"]'::jsonb,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  'medium',
  TRUE
)
ON CONFLICT (slug) DO UPDATE SET
  name                = EXCLUDED.name,
  category            = EXCLUDED.category,
  sub_category        = EXCLUDED.sub_category,
  wilaya              = EXCLUDED.wilaya,
  commune             = EXCLUDED.commune,
  address             = EXCLUDED.address,
  website_url         = EXCLUDED.website_url,
  contact_email       = EXCLUDED.contact_email,
  facebook_page       = EXCLUDED.facebook_page,
  instagram_username  = COALESCE(institutions.instagram_username, EXCLUDED.instagram_username),
  bac_required        = EXCLUDED.bac_required,
  diploma_type        = EXCLUDED.diploma_type,
  mesrs_recognized    = EXCLUDED.mesrs_recognized,
  intl_equivalence    = EXCLUDED.intl_equivalence,
  languages           = EXCLUDED.languages,
  annual_cost_range   = EXCLUDED.annual_cost_range,
  admission_type      = EXCLUDED.admission_type,
  promo_size          = EXCLUDED.promo_size,
  internship_provided = EXCLUDED.internship_provided,
  internship_duration = EXCLUDED.internship_duration,
  programmes          = EXCLUDED.programmes,
  real_outcomes       = EXCLUDED.real_outcomes,
  insertion_rate      = EXCLUDED.insertion_rate,
  passerelles         = EXCLUDED.passerelles,
  corporate_partners  = EXCLUDED.corporate_partners,
  school_partners     = EXCLUDED.school_partners,
  boarding_available  = EXCLUDED.boarding_available,
  transport_available = EXCLUDED.transport_available,
  canteen_available   = EXCLUDED.canteen_available,
  elearning_platform  = EXCLUDED.elearning_platform,
  data_confidence     = 'medium',
  is_active           = TRUE;

